import {Metadata} from 'next';
import {redirect} from 'next/navigation';

import UserProfilePage from '@/views/UserProfile';

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by Home Page',
};
type Props = {
  params: Promise<{id: string}>;
  searchParams: Promise<Record<string, string>>;
};

export default async function asyncUserProfile({params, searchParams}: Props) {
  const {id} = await params;
  const {postId, action} = await searchParams;

  if (postId && action) {
    redirect(`/profile/${id}?postId=${postId}`);
  }

  return <UserProfilePage id={id} />;
}
