import {Metadata} from 'next';

import HomePage from '@/pages/HomePage';

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by Home Page',
};

export default function Home() {
  return <HomePage />;
}
