import {Metadata} from 'next';
import Link from 'next/link';

import s from './page.module.scss';

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by Home Page',
};

export default function HomePage() {
  return (
    <div className={s.page}>
      <Link href={'/profile'}>Profile</Link>
      <Link href={'/settings'}>Settings</Link>
    </div>
  );
}
